In [41]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [17]:
print(os.getcwd())

/Users/angela/DSprojects

In [19]:
data = pd.read_csv('./DataExtract.csv', header=2)

In [21]:
data.head()

,pdc,num_ip_post,total_los_post,num_op_post,num_er_post,num_ndc_post,num_gpi6_post,adjust_total_30d_post,generic_rate_post,post_ip_flag,...,brand_cost,ratio_G_total_cost,numofgen_post,numofbrand_post,generic_cost_post,brand_cost_post,ratio_G_total_cost_post,pdc_80_flag,drug_class,patient_key
0,0.894444,0,0,8,0,17,3,6.966667,1.000000,0,...,239.699550,0.710850,17,0,4332.043215,0.000000,1.000000,1,*ANTICOAGULANTS*,121
1,0.333333,0,0,4,0,15,5,14.466667,0.101382,0,...,2984.927229,0.010155,2,13,196.359216,3001.501507,0.061403,0,*ANTIDIABETICS*,168
2,0.077778,0,0,32,0,11,7,3.833333,0.739130,0,...,0.000000,1.000000,10,1,203.603270,1154.818505,0.149882,0,*ANTICOAGULANTS*,267
3,0.333333,0,0,57,0,16,6,24.000000,0.958333,0,...,160.804799,0.291008,15,1,140.952640,265.057382,0.347165,0,*ANTICOAGULANTS*,468
4,0.866667,0,0,5,0,16,4,18.000000,0.888889,0,...,0.000000,1.000000,14,2,671.755173,735.661568,0.477297,1,*ANTIDIABETICS*,499

In [23]:
AD = data[data['drug_class'] == '*ANTIDIABETICS*']

In [29]:
patient_filter = AD[(AD['pdc_80_flag'] ==1) & (AD['brand_cost_post'] > 735)]

In [31]:
patient_filter

,pdc,num_ip_post,total_los_post,num_op_post,num_er_post,num_ndc_post,num_gpi6_post,adjust_total_30d_post,generic_rate_post,post_ip_flag,...,brand_cost,ratio_G_total_cost,numofgen_post,numofbrand_post,generic_cost_post,brand_cost_post,ratio_G_total_cost_post,pdc_80_flag,drug_class,patient_key
4,0.866667,0,0,5,0,16,4,18.000000,0.888889,0,...,0.000000,1.000000,14,2,671.755173,735.661568,0.477297,1,*ANTIDIABETICS*,499
21,0.977778,0,0,9,0,40,9,42.533333,0.835423,0,...,1345.104492,0.339094,33,7,842.908516,1695.649323,0.332042,1,*ANTIDIABETICS*,1852
34,0.900000,0,0,7,0,37,12,36.000000,0.627778,0,...,3239.094592,0.122681,25,12,376.675746,5461.857232,0.064515,1,*ANTIDIABETICS*,3427
38,0.966667,0,0,4,0,28,6,27.333333,0.780488,0,...,0.000000,1.000000,22,6,703.214745,1667.628096,0.296610,1,*ANTIDIABETICS*,3983
40,0.827778,0,0,0,0,49,13,47.133333,0.877652,0,...,1544.676848,0.406289,42,7,1569.525523,2133.939243,0.423799,1,*ANTIDIABETICS*,4345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489,0.961111,3,11,13,3,87,17,75.900000,0.779534,1,...,2303.793020,0.214243,67,20,1675.541338,3411.837924,0.329353,1,*ANTIDIABETICS*,510950
3494,0.888889,2,30,35,1,88,16,83.466667,0.533147,1,...,734.085933,0.190072,47,41,911.805080,4649.972588,0.163941,1,*ANTIDIABETICS*,512465
3506,0.966667,1,2,22,0,32,13,65.100000,0.831029,1,...,0.000000,1.000000,27,5,2284.007798,2762.826326,0.452562,1,*ANTIDIABETICS*,516133
3509,0.900000,0,0,5,0,9,5,27.000000,0.555556,0,...,956.496326,0.299848,5,4,116.540967,1432.960296,0.075212,1,*ANTIDIABETICS*,516515
3522,0.900000,0,0,13,0,33,18,42.966667,0.674942,0,...,409.683847,0.442947,23,10,285.496499,3618.763847,0.073124,1,*ANTIDIABETICS*,517310

In [33]:
groupby = AD.groupby('pdc_80_flag')['generic_cost_post'].transform('median')

In [35]:
groupby

1       109.730365
4       190.788893
5       109.730365
8       109.730365
16      190.788893
           ...
3528    109.730365
3529    190.788893
3530    109.730365
3532    109.730365
3533    190.788893
Name: generic_cost_post, Length: 1722, dtype: float64

In [37]:
numeric_cols = ['numofgen_post', 'numofbrand_post']
for col in numeric_cols:
    data[col] = data[col].fillna(data[col].median())